=== Appendium/jtreemap/trunk/org.jense.ktreemap/TreeMap.dtd
<?xml version='1.0' encoding='ISO-8859-1'?>
<!ELEMENT root (label,(branch |leaf)*)>
<!ELEMENT branch (label,(branch|leaf)*)>
<!ELEMENT leaf (label,weight,value) >
<!ELEMENT label (#PCDATA) >
<!ELEMENT weight (#PCDATA) >
<!ELEMENT value (#PCDATA) >

=== Appendium/jtreemap/trunk/JTreeMap/dataDump.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE root SYSTEM "TreeMap.dtd" >
	<root>
		<label>Node 0</label>
		<branch>
			<label>Node 1</label>
			<leaf>
				<label>leaf 2</label>
				<weight>40.0</weight>
				<value>40.0</value>
			</leaf>
			<leaf>
				<label>leaf 3</label>
				<weight>19.0</weight>
				<value>19.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 4</label>
			<leaf>
				<label>leaf 5</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 6</label>
			<leaf>
				<label>leaf 7</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 8</label>
			<leaf>
				<label>leaf 9</label>
				<weight>7.0</weight>
				<value>7.0</value>
			</leaf>
			<leaf>
				<label>leaf 10</label>
				<weight>6.0</weight>
				<value>6.0</value>
			</leaf>
			<leaf>
				<label>leaf 11</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 12</label>
				<weight>5.0</weight>
				<value>6.0</value>
			</leaf>
			<leaf>
				<label>leaf 13</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 14</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 15</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 16</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 17</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>leaf 18</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 19</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 20</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 21</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 22</label>
				<weight>4.0</weight>
				<value>5.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 23</label>
			<leaf>
				<label>leaf 24</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>leaf 25</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 26</label>
			<leaf>
				<label>leaf 27</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 28</label>
			<leaf>
				<label>leaf 29</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 30</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>leaf 31</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 32</label>
				<weight>4.0</weight>
				<value>4.0</value>
			</leaf>
			<leaf>
				<label>leaf 33</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>leaf 34</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 35</label>
			<leaf>
				<label>leaf 36</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 37</label>
			<leaf>
				<label>leaf 38</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 39</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 40</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>leaf 41</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 42</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 43</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 44</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 45</label>
				<weight>1.0</weight>
				<value>0.0</value>
			</leaf>
			<leaf>
				<label>leaf 46</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 47</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 48</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 49</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 50</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 51</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 52</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 53</label>
				<weight>1.0</weight>
				<value>0.0</value>
			</leaf>
			<leaf>
				<label>leaf 54</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 55</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 56</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 57</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 58</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>leaf 59</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 60</label>
			<leaf>
				<label>leaf 61</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 62</label>
			<leaf>
				<label>leaf 63</label>
				<weight>7.0</weight>
				<value>0.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 64</label>
			<branch>
				<label>Node 641</label>
				<leaf>
					<label>leaf 6411</label>
					<weight>10.0</weight>
					<value>10.0</value>
				</leaf>
				<leaf>
					<label>leaf 6412</label>
					<weight>8.0</weight>
					<value>10.0</value>
				</leaf>
			</branch>	
			<leaf>
				<label>leaf 65</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>leaf 66</label>
				<weight>34.0</weight>
				<value>34.0</value>
			</leaf>
			<leaf>
				<label>leaf 67</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 68</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 69</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 70</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 71</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 72</label>
				<weight>33.0</weight>
				<value>33.0</value>
			</leaf>
			<leaf>
				<label>leaf 73</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 74</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 75</label>
			<leaf>
				<label>leaf 76</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 77</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 78</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 79</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 80</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>leaf 81</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 82</label>
			<leaf>
				<label>leaf 83</label>
				<weight>25.0</weight>
				<value>25.0</value>
			</leaf>
			<leaf>
				<label>leaf 84</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
			<leaf>
				<label>leaf 85</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
		</branch>
	</root>

=== Appendium/jtreemap/KTreeMap/src/main/conf/dataDump.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE root SYSTEM "TreeMap.dtd" >
	<root>
		<label>Node 0</label>
		<branch>
			<label>Node 1</label>
			<leaf>
				<label>Node 2</label>
				<weight>40.0</weight>
				<value>40.0</value>
			</leaf>
			<leaf>
				<label>Node 3</label>
				<weight>19.0</weight>
				<value>19.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 4</label>
			<leaf>
				<label>Node 5</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 6</label>
			<leaf>
				<label>Node 7</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 8</label>
			<leaf>
				<label>Node 9</label>
				<weight>7.0</weight>
				<value>7.0</value>
			</leaf>
			<leaf>
				<label>Node 10</label>
				<weight>6.0</weight>
				<value>6.0</value>
			</leaf>
			<leaf>
				<label>Node 11</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 12</label>
				<weight>5.0</weight>
				<value>6.0</value>
			</leaf>
			<leaf>
				<label>Node 13</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 14</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 15</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 16</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 17</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>Node 18</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 19</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 20</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 21</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 22</label>
				<weight>4.0</weight>
				<value>5.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 23</label>
			<leaf>
				<label>Node 24</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>Node 25</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 26</label>
			<leaf>
				<label>Node 27</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 28</label>
			<leaf>
				<label>Node 29</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 30</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>Node 31</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 32</label>
				<weight>4.0</weight>
				<value>4.0</value>
			</leaf>
			<leaf>
				<label>Node 33</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>Node 34</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 35</label>
			<leaf>
				<label>Node 36</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 37</label>
			<leaf>
				<label>Node 38</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 39</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 40</label>
				<weight>3.0</weight>
				<value>3.0</value>
			</leaf>
			<leaf>
				<label>Node 41</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 42</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 43</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 44</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 45</label>
				<weight>1.0</weight>
				<value>0.0</value>
			</leaf>
			<leaf>
				<label>Node 46</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 47</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 48</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 49</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 50</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 51</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 52</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 53</label>
				<weight>1.0</weight>
				<value>0.0</value>
			</leaf>
			<leaf>
				<label>Node 54</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 55</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 56</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 57</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 58</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<leaf>
			<label>Node 59</label>
			<weight>0.0</weight>
			<value>0.0</value>
		</leaf>
		<branch>
			<label>Node 60</label>
			<leaf>
				<label>Node 61</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 62</label>
			<leaf>
				<label>Node 63</label>
				<weight>7.0</weight>
				<value>0.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 64</label>
			<leaf>
				<label>Node 65</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
			<leaf>
				<label>Node 66</label>
				<weight>34.0</weight>
				<value>34.0</value>
			</leaf>
			<leaf>
				<label>Node 67</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 68</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 69</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 70</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 71</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 72</label>
				<weight>33.0</weight>
				<value>33.0</value>
			</leaf>
			<leaf>
				<label>Node 73</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 74</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 75</label>
			<leaf>
				<label>Node 76</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 77</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 78</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 79</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 80</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
			<leaf>
				<label>Node 81</label>
				<weight>1.0</weight>
				<value>1.0</value>
			</leaf>
		</branch>
		<branch>
			<label>Node 82</label>
			<leaf>
				<label>Node 83</label>
				<weight>25.0</weight>
				<value>25.0</value>
			</leaf>
			<leaf>
				<label>Node 84</label>
				<weight>2.0</weight>
				<value>2.0</value>
			</leaf>
			<leaf>
				<label>Node 85</label>
				<weight>5.0</weight>
				<value>5.0</value>
			</leaf>
		</branch>
	</root>

=== Appendium/jtreemap/JTreeMap/TreeMap.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE root SYSTEM "TreeMap.dtd" >

<root>
  <label>Root</label>
  <branch>
    <label>branch1</label>
    <branch>
	<label>branch11</label>
	<leaf>
	  <label>leaf111</label>
	  <weight>1.0</weight>
	  <value>0.5</value>
	</leaf>
	<leaf>
	  <label>leaf112</label>
	  <weight>2.0</weight>
	  <value>-5.0</value>
	</leaf>
	<leaf>
	  <label>leaf113</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf114</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf115</label>
	  <weight>0.25</weight>
	  <value>-5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch12</label>
	<leaf>
	  <label>leaf121</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf122</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf123</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf124</label>
	  <weight>3.0</weight>
	  <value>-2.0</value>
	</leaf>
	<leaf>
	  <label>leaf125</label>
	  <weight>0.25</weight>
	  <value>5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch13</label>
	<leaf>
	  <label>leaf131</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf132</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf133</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf134</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
    </branch>
    <leaf>
	<label>leaf14</label>
	<weight>3.0</weight>
	<value>2.0</value>
    </leaf>
    <leaf>
	<label>leaf15</label>
	<weight>2.0</weight>
	<value>-5.0</value>
    </leaf>
  </branch>
  <branch>
    <label>branch2</label>
    <branch>
	<label>branch21</label>
	<leaf>
	  <label>leaf211</label>
	  <weight>1.0</weight>
	  <value>-1.0</value>
	</leaf>
	<leaf>
	  <label>leaf212</label>
	  <weight>2.0</weight>
	  <value>-5.0</value>
	</leaf>
	<leaf>
	  <label>leaf213</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf214</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf215</label>
	  <weight>0.25</weight>
	  <value>5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch22</label>
	<leaf>
	  <label>leaf221</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf222</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf223</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf224</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
    </branch>
  </branch>
  <branch>
    <label>branch3</label>
    <branch>
	<label>branch31</label>
	<leaf>
	  <label>leaf311</label>
	  <weight>1.0</weight>
	  <value>-1.0</value>
	</leaf>
	<leaf>
	  <label>leaf312</label>
	  <weight>2.0</weight>
	  <value>-5.0</value>
	</leaf>
	<leaf>
	  <label>leaf313</label>
	  <weight>0.5</weight>
	  <value>-2.0</value>
	</leaf>
	<leaf>
	  <label>leaf314</label>
	  <weight>3.0</weight>
	  <value>-2.0</value>
	</leaf>
	<leaf>
	  <label>leaf315</label>
	  <weight>0.25</weight>
	  <value>-5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch32</label>
	<leaf>
	  <label>leaf321</label>
	  <weight>1.0</weight>
	  <value>-1.0</value>
	</leaf>
	<leaf>
	  <label>leaf322</label>
	  <weight>2.0</weight>
	  <value>-5.0</value>
	</leaf>
	<leaf>
	  <label>leaf323</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf324</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf325</label>
	  <weight>0.25</weight>
	  <value>-5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch33</label>
	<leaf>
	  <label>leaf331</label>
	  <weight>1.0</weight>
	  <value>-1.0</value>
	</leaf>
	<leaf>
	  <label>leaf332</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf333</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf334</label>
	  <weight>3.0</weight>
	  <value>-2.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch34</label>
	<leaf>
	  <label>leaf341</label>
	  <weight>1.0</weight>
	  <value>-1.0</value>
	</leaf>
	<leaf>
	  <label>leaf342</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf343</label>
	  <weight>0.5</weight>
	  <value>-2.0</value>
	</leaf>
    </branch>
  </branch>
  <branch>
    <label>branch4</label>
    <branch>
	<label>branch41</label>
	<leaf>
	  <label>leaf411</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf412</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf413</label>
	  <weight>0.5</weight>
	  <value>2.5</value>
	</leaf>
	<leaf>
	  <label>leaf414</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf415</label>
	  <weight>0.25</weight>
	  <value>-5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch42</label>
	<leaf>
	  <label>leaf421</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf422</label>
	  <weight>2.0</weight>
	  <value>5.0</value>
	</leaf>
	<leaf>
	  <label>leaf423</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf424</label>
	  <weight>3.0</weight>
	  <value>2.1</value>
	</leaf>
	<leaf>
	  <label>leaf425</label>
	  <weight>0.25</weight>
	  <value>-5.0</value>
	</leaf>
    </branch>
    <branch>
	<label>branch43</label>
	<leaf>
	  <label>leaf431</label>
	  <weight>1.0</weight>
	  <value>1.0</value>
	</leaf>
	<leaf>
	  <label>leaf432</label>
	  <weight>2.0</weight>
	  <value>-5.0</value>
	</leaf>
	<leaf>
	  <label>leaf433</label>
	  <weight>0.5</weight>
	  <value>2.0</value>
	</leaf>
	<leaf>
	  <label>leaf434</label>
	  <weight>3.0</weight>
	  <value>2.0</value>
	</leaf>
    </branch>
  </branch>
</root>
